
# Live Office Hour 2

## Schedule and Zoom link

* The second live office hour session will take place on Thursday 18th January at 4-5pm EST via [Zoom](https://uofglasgow.zoom.us/j/85258521368) (Meeting ID: 852 5852 1368). 
* The waiting room will be enabled. Please ensure that your Zoom name is set to the name that you used to register with the *All of Us* Researcher Academy otherwise you may not be allowed entry to the session.

## Content

Live office hours are primarily an opportunity for you to ask questions to the instructors, get support with any problems you have been having, or request additional information on any aspect of the course so far.

* Emily will lead a Q&A session on material covered in the workbook from Week 2 
* Javan will lead a Q&A session on how the skills you have learned transfer to the *All of Us* Researcher Workbench. 
* If you have any specific analytic techniques that you like to use in R that we have not covered, please let us know in advance of the office hours via the [Q&A form](https://forms.gle/bFeRK2wQkw9i3dpW6) and we will collate resources to help support your goals.

## Pre-requisites

* Before joining the office hour, please ensure that you have worked through all the material from Week 2 - consult the Progress Tracker if you're not sure what you need to do.
* You can ask questions on the day, but you can also complete the [Q&A form](https://forms.gle/bFeRK2wQkw9i3dpW6) in advance to let your instructors know what you would like the session to focus on.